theme: minima
title: krishna kakade
author: krishnadevz
email: krishnadevz@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 About me here you find content related to technology/Me/Science/Web Development 
 Learning FullStack-Developer,Passion for ComputersğŸ±â€ğŸ’» and 
  Science,Protonï¸â„ <MyWorldFoundedInğŸ±â€ğŸ’»ğŸ’»ğŸŒ„ğŸ’­/> 

# social links
twitter_username: krishnadevz # DO NOT include the @ character, or else the build will fail!
github_username:  krishnadevz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
